name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        cd frontend && npm ci
        cd ../backend && npm ci
        
    - name: Run Frontend Tests
      run: |
        cd frontend
        npm run test:ci
        
    - name: Run Backend Tests
      run: |
        cd backend
        npm run test:ci
        
    - name: Run E2E Tests
      run: |
        cd frontend
        npm run cypress:run
        
    - name: Upload Test Coverage
      uses: codecov/codecov-action@v2

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Build Frontend
      run: |
        cd frontend
        npm ci
        npm run build
        
    - name: Build Backend
      run: |
        cd backend
        npm ci
        npm run build
        
    - name: Upload Frontend Artifact
      uses: actions/upload-artifact@v2
      with:
        name: frontend-build
        path: frontend/build
        
    - name: Upload Backend Artifact
      uses: actions/upload-artifact@v2
      with:
        name: backend-build
        path: backend/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Download Frontend Build
      uses: actions/download-artifact@v2
      with:
        name: frontend-build
        path: frontend/build
        
    - name: Download Backend Build
      uses: actions/download-artifact@v2
      with:
        name: backend-build
        path: backend/dist
        
    - name: Deploy to Production
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        npm install -g firebase-tools
        firebase deploy --token "$FIREBASE_TOKEN"
